title: Eddie Husarcik, MD
description: Home Page
theme: just-the-docs

url: https://husarcik.github.io

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# jekyll plugins
plugins:
  - jekyll-seo-tag
