remote_theme: pmarsceill/just-the-docs

title: Eddie Husarcik

# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
search.button: true
